export { default as Home1 } from "./Home1/Home1";
export { default as Home2 } from "./Home2/Home2";
export { default as About } from "./About/About";
export { default as Blog } from "./Blog/Blog";
export { default as Contact } from "./Contact/Contact";
export { default as Footer } from "./Footer/Footer";
export { default as Gallery } from "./Gallery/Gallery";
export { default as Service } from "./Service/Service";
export { default as Team } from "./Team/Team";
